import csv
import io
import math
import zipfile
from dataclasses import dataclass
from pathlib import Path


EXPECTED_ENTRIES = {"telemetry.csv", "session.txt"}
BOOLEAN_COLUMNS = {
    "on_ground",
    "motion_simulation",
    "axis_elevator_set_valid",
    *(f"contact_{index}_on_ground" for index in range(20)),
    *(f"controller_{index}_raw_y_valid" for index in range(8)),
}


@dataclass(frozen=True)
class CaptureFacts:
    sample_count: int
    uncompressed_bytes: int


def _session_values(content: bytes) -> dict[str, str]:
    if len(content) > 8192:
        raise ValueError("session metadata is too large")
    text = content.decode("utf-8")
    result: dict[str, str] = {}
    for line in text.splitlines():
        if not line or line.startswith("Generated by "):
            continue
        if "=" not in line:
            raise ValueError("session metadata contains an invalid line")
        key, value = line.split("=", 1)
        if not key or key in result or len(key) > 64 or len(value) > 1024:
            raise ValueError("session metadata is malformed")
        result[key] = value
    return result


def validate_capture(path: Path, expected_header: str, maximum_uncompressed: int) -> CaptureFacts:
    with zipfile.ZipFile(path, "r") as archive:
        infos = archive.infolist()
        names = [info.filename for info in infos]
        if len(infos) != 2 or set(names) != EXPECTED_ENTRIES or len(set(names)) != 2:
            raise ValueError("archive must contain exactly telemetry.csv and session.txt")

        total_uncompressed = 0
        for info in infos:
            if info.is_dir() or info.flag_bits & 0x1:
                raise ValueError("directories and encrypted entries are not accepted")
            if "\\" in info.filename or "/" in info.filename or info.filename.startswith("."):
                raise ValueError("archive entry path is unsafe")
            total_uncompressed += info.file_size
            if total_uncompressed > maximum_uncompressed:
                raise ValueError("archive expands beyond the configured limit")
            if info.compress_size == 0 or info.file_size / info.compress_size > 25:
                raise ValueError("archive compression ratio exceeds policy")

        session = _session_values(archive.read("session.txt"))
        if session.get("telemetry_schema") != "5":
            raise ValueError("unsupported telemetry schema")
        if session.get("source_period") != "SIM_FRAME":
            raise ValueError("telemetry is not a SIM_FRAME capture")

        expected_columns = expected_header.split(",")
        index = {name: position for position, name in enumerate(expected_columns)}
        sample_count = 0
        previous_sequence: int | None = None
        with archive.open("telemetry.csv", "r") as raw:
            text = io.TextIOWrapper(raw, encoding="utf-8", errors="strict", newline="")
            reader = csv.reader(text)
            try:
                header = next(reader)
            except StopIteration as exc:
                raise ValueError("telemetry.csv is empty") from exc
            if header != expected_columns:
                raise ValueError("telemetry.csv header is not schema v5")

            for row in reader:
                sample_count += 1
                if sample_count > 30000:
                    raise ValueError("capture contains more than 30000 samples")
                if len(row) != len(expected_columns):
                    raise ValueError("telemetry row width does not match schema")
                if sum(len(value) for value in row) > 8192:
                    raise ValueError("telemetry row is too large")
                try:
                    sequence = int(row[index["sequence"]])
                except ValueError as exc:
                    raise ValueError("sequence is not an integer") from exc
                if previous_sequence is not None and sequence <= previous_sequence:
                    raise ValueError("sequence is not strictly increasing")
                previous_sequence = sequence

                for column, value in zip(expected_columns, row):
                    if column in BOOLEAN_COLUMNS:
                        if value not in {"0", "1"}:
                            raise ValueError(f"{column} is not boolean")
                        continue
                    try:
                        numeric = float(value)
                    except ValueError as exc:
                        raise ValueError(f"{column} is not numeric") from exc
                    if not math.isfinite(numeric):
                        raise ValueError(f"{column} is not finite")

        if sample_count == 0:
            raise ValueError("capture contains no samples")
        try:
            declared_count = int(session["sample_count"])
        except (KeyError, ValueError) as exc:
            raise ValueError("session sample_count is missing or invalid") from exc
        if declared_count != sample_count:
            raise ValueError("session sample_count does not match telemetry.csv")

        return CaptureFacts(sample_count=sample_count, uncompressed_bytes=total_uncompressed)
