import argparse
import base64
import hashlib
import io
import json
import secrets
import urllib.error
import urllib.request
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa

from cleanup_e2e import cleanup

USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) MSFS-Landing-Stats-Telemetry/1"


def timestamp() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="milliseconds").replace("+00:00", "Z")


def nonce() -> str:
    return base64.urlsafe_b64encode(secrets.token_bytes(16)).decode("ascii").rstrip("=")


def post_json(url: str, value: dict) -> dict:
    body = json.dumps(value, separators=(",", ":")).encode("utf-8")
    request = urllib.request.Request(
        url,
        data=body,
        method="POST",
        headers={"Content-Type": "application/json", "User-Agent": USER_AGENT},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return json.load(response)
    except urllib.error.HTTPError as exc:
        raise RuntimeError(f"HTTP {exc.code}: {exc.read().decode('utf-8', errors='replace')}") from exc


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--endpoint", required=True)
    parser.add_argument("--cleanup-data-root")
    args = parser.parse_args()
    endpoint = args.endpoint.rstrip("/") + "/"

    private = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public = private.public_key().public_numbers()
    modulus = base64.b64encode(public.n.to_bytes(256, "big")).decode("ascii")
    exponent = base64.b64encode(public.e.to_bytes(3, "big")).decode("ascii")
    install_id = secrets.token_hex(16)
    sent_at = timestamp()
    enroll_nonce = nonce()
    enrollment = (
        "MSFS-LANDING-STATS-ENROLLMENT-V1\n"
        f"install_id={install_id}\n"
        f"sent_at_utc={sent_at}\n"
        f"nonce={enroll_nonce}\n"
        f"public_modulus={modulus}\n"
        f"public_exponent={exponent}\n"
    ).encode("ascii")
    post_json(
        endpoint + "v1/enroll",
        {
            "install_id": install_id,
            "sent_at_utc": sent_at,
            "nonce": enroll_nonce,
            "public_modulus": modulus,
            "public_exponent": exponent,
            "signature": base64.b64encode(private.sign(enrollment, padding.PKCS1v15(), hashes.SHA256())).decode("ascii"),
        },
    )

    header = (Path(__file__).resolve().parents[1] / "schema-v5.header").read_text(encoding="utf-8").strip()
    row = ["0"] * len(header.split(","))
    row[0] = "1"
    archive_bytes = io.BytesIO()
    with zipfile.ZipFile(archive_bytes, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("telemetry.csv", header + "\n" + ",".join(row) + "\n")
        archive.writestr(
            "session.txt",
            "Generated by e2e test\ntelemetry_schema=5\nsource_period=SIM_FRAME\nsample_count=1\n",
        )
    body = archive_bytes.getvalue()
    digest = hashlib.sha256(body).hexdigest()
    sent_at = timestamp()
    capture_nonce = nonce()
    canonical = (
        "MSFS-LANDING-STATS-TELEMETRY-V1\n"
        f"install_id={install_id}\n"
        f"sent_at_utc={sent_at}\n"
        f"nonce={capture_nonce}\n"
        f"sha256={digest}\n"
        f"size={len(body)}\n"
        "schema=5\n"
        "app_version=0.7.0\n"
    ).encode("ascii")
    request = urllib.request.Request(
        endpoint + "v1/captures",
        data=body,
        method="POST",
        headers={
            "Content-Type": "application/zip",
            "User-Agent": USER_AGENT,
            "X-Install-Id": install_id,
            "X-Sent-At-Utc": sent_at,
            "X-Capture-Nonce": capture_nonce,
            "X-Capture-SHA256": digest,
            "X-Capture-Size": str(len(body)),
            "X-Telemetry-Schema": "5",
            "X-App-Version": "0.7.0",
            "X-Signature": base64.b64encode(private.sign(canonical, padding.PKCS1v15(), hashes.SHA256())).decode("ascii"),
        },
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        result = json.load(response)
    cleaned = None
    if args.cleanup_data_root:
        cleaned = cleanup(args.cleanup_data_root, install_id)
    print(json.dumps({"install_id": install_id, "sha256": digest, "cleaned_captures": cleaned, **result}, separators=(",", ":")))


if __name__ == "__main__":
    main()
