import base64
import concurrent.futures
import json
import sqlite3
import tempfile
import unittest
import zipfile
from pathlib import Path

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa

from app.security import canonical_capture, public_key, verify_signature
from app.store import InstallationRegistryFullError, Store
from app.validation import validate_capture


ROOT = Path(__file__).resolve().parents[1]
HEADER = (ROOT / "schema-v5.header").read_text(encoding="utf-8").strip()


class CaptureValidationTests(unittest.TestCase):
    def _archive(self, directory: Path, row_values=None, session_count=1) -> Path:
        values = row_values or ["0"] * len(HEADER.split(","))
        values[0] = "1"
        path = directory / "capture.zip"
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("telemetry.csv", HEADER + "\n" + ",".join(values) + "\n")
            archive.writestr(
                "session.txt",
                "Generated by test\n"
                "telemetry_schema=5\n"
                "source_period=SIM_FRAME\n"
                f"sample_count={session_count}\n",
            )
        return path

    def _flight_archive(self, directory: Path, replay: bool) -> Path:
        columns = HEADER.split(",")
        index = {name: position for position, name in enumerate(columns)}
        rows = []
        latitude = 42.0
        altitude = 1200.0
        for sequence in range(18):
            values = ["0"] * len(columns)
            values[index["sequence"]] = str(sequence + 1)
            values[index["simulation_time_s"]] = str(sequence)
            values[index["on_ground"]] = "1" if sequence == 17 else "0"
            values[index["motion_simulation"]] = "1"
            values[index["latitude_deg"]] = format(latitude - sequence / 1800.0, ".9f")
            values[index["longitude_deg"]] = "23.0"
            values[index["plane_altitude_ft"]] = str(altitude - sequence * 10.0)
            values[index["ground_speed_kt"]] = "0" if replay else "120"
            values[index["airspeed_indicated_kt"]] = "5" if replay else "115"
            values[index["velocity_world_y_fps"]] = "0" if replay else "-10"
            rows.append(values)

        path = directory / ("replay.zip" if replay else "live.zip")
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
            archive.writestr(
                "telemetry.csv",
                HEADER + "\n" + "\n".join(",".join(row) for row in rows) + "\n",
            )
            archive.writestr(
                "session.txt",
                "Generated by test\n"
                "telemetry_schema=5\n"
                "source_period=SIM_FRAME\n"
                f"sample_count={len(rows)}\n",
            )
        return path

    def _bug_report_archive(self, directory: Path) -> Path:
        values = ["0"] * len(HEADER.split(","))
        values[0] = "1"
        path = directory / "bug-report.zip"
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("telemetry.csv", HEADER + "\n" + ",".join(values) + "\n")
            archive.writestr(
                "session.txt",
                "Generated by test\n"
                "telemetry_schema=5\n"
                "source_period=SIM_FRAME\n"
                "sample_count=1\n"
                "capture_kind=bug_report\n"
                "bug_report_format=1\n"
                "episode_id=42\n"
                "landing_count=1\n",
            )
            archive.writestr(
                "landing-results.json",
                json.dumps(
                    {
                        "format_version": 1,
                        "episode_id": 42,
                        "records": [{"summary": {"id": "landing"}}],
                    }
                ),
            )
        return path

    def test_accepts_current_schema_archive(self):
        with tempfile.TemporaryDirectory() as value:
            facts = validate_capture(self._archive(Path(value)), HEADER, 64 * 1024 * 1024)
            self.assertEqual(1, facts.sample_count)
            self.assertGreater(facts.uncompressed_bytes, 0)
            self.assertEqual("raw_debug", facts.capture_kind)

    def test_accepts_bug_report_with_calculated_landing(self):
        with tempfile.TemporaryDirectory() as value:
            facts = validate_capture(
                self._bug_report_archive(Path(value)), HEADER, 64 * 1024 * 1024
            )
            self.assertEqual(1, facts.sample_count)
            self.assertEqual("bug_report", facts.capture_kind)

    def test_rejects_non_finite_value(self):
        with tempfile.TemporaryDirectory() as value:
            row = ["0"] * len(HEADER.split(","))
            row[0] = "1"
            row[1] = "nan"
            with self.assertRaisesRegex(ValueError, "not finite"):
                validate_capture(self._archive(Path(value), row), HEADER, 64 * 1024 * 1024)

    def test_rejects_unexpected_member(self):
        with tempfile.TemporaryDirectory() as value:
            path = self._archive(Path(value))
            with zipfile.ZipFile(path, "a", compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr("surprise.bin", b"garbage")
            with self.assertRaisesRegex(ValueError, "unexpected"):
                validate_capture(path, HEADER, 64 * 1024 * 1024)

    def test_rejects_missing_session_metadata(self):
        with tempfile.TemporaryDirectory() as value:
            directory = Path(value)
            values = ["0"] * len(HEADER.split(","))
            values[0] = "1"
            path = directory / "missing-session.zip"
            with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr("telemetry.csv", HEADER + "\n" + ",".join(values) + "\n")
                archive.writestr("landing-results.json", "{}")
            with self.assertRaisesRegex(ValueError, "session metadata"):
                validate_capture(path, HEADER, 64 * 1024 * 1024)

    def test_rejects_non_zip_as_validation_error(self):
        with tempfile.TemporaryDirectory() as value:
            path = Path(value) / "not-a-zip.zip"
            path.write_bytes(b"not a zip archive")
            with self.assertRaisesRegex(ValueError, "malformed"):
                validate_capture(path, HEADER, 64 * 1024 * 1024)

    def test_rejects_csv_parser_overflow_as_validation_error(self):
        with tempfile.TemporaryDirectory() as value:
            directory = Path(value)
            path = directory / "oversized-field.zip"
            with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_STORED) as archive:
                archive.writestr("telemetry.csv", HEADER + "\n" + "1" * 200_000 + "\n")
                archive.writestr(
                    "session.txt",
                    "telemetry_schema=5\nsource_period=SIM_FRAME\nsample_count=1\n",
                )
            with self.assertRaisesRegex(ValueError, "malformed"):
                validate_capture(path, HEADER, 64 * 1024 * 1024)

    def test_rejects_bug_report_without_results(self):
        with tempfile.TemporaryDirectory() as value:
            directory = Path(value)
            values = ["0"] * len(HEADER.split(","))
            values[0] = "1"
            path = directory / "bug-report-without-results.zip"
            with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr("telemetry.csv", HEADER + "\n" + ",".join(values) + "\n")
                archive.writestr(
                    "session.txt",
                    "telemetry_schema=5\nsource_period=SIM_FRAME\nsample_count=1\n"
                    "capture_kind=bug_report\nbug_report_format=1\nlanding_count=1\n",
                )
            with self.assertRaisesRegex(ValueError, "capture kind"):
                validate_capture(path, HEADER, 64 * 1024 * 1024)

    def test_rejects_count_mismatch(self):
        with tempfile.TemporaryDirectory() as value:
            with self.assertRaisesRegex(ValueError, "sample_count"):
                validate_capture(self._archive(Path(value), session_count=2), HEADER, 64 * 1024 * 1024)

    def test_rejects_replay_kinematics_but_accepts_consistent_live_flight(self):
        with tempfile.TemporaryDirectory() as value:
            directory = Path(value)
            live = validate_capture(
                self._flight_archive(directory, replay=False), HEADER, 64 * 1024 * 1024
            )
            self.assertEqual(18, live.sample_count)
            with self.assertRaisesRegex(ValueError, "replay-like"):
                validate_capture(
                    self._flight_archive(directory, replay=True), HEADER, 64 * 1024 * 1024
                )


class SignatureTests(unittest.TestCase):
    def test_capture_signature_is_bound_to_hash_and_size(self):
        private = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        numbers = private.public_key().public_numbers()
        modulus = base64.b64encode(numbers.n.to_bytes(256, "big")).decode("ascii")
        exponent = base64.b64encode(numbers.e.to_bytes(3, "big")).decode("ascii")
        message = canonical_capture(
            "a" * 32,
            "2026-08-05T12:00:00Z",
            "A" * 22,
            "b" * 64,
            1234,
            5,
            "0.7.0",
        )
        signature = private.sign(message, padding.PKCS1v15(), hashes.SHA256())
        encoded = base64.b64encode(signature).decode("ascii")
        verify_signature(public_key(modulus, exponent), message, encoded)
        with self.assertRaisesRegex(ValueError, "verification failed"):
            verify_signature(public_key(modulus, exponent), message + b"x", encoded)


class ByteBudgetTests(unittest.TestCase):
    def test_byte_budgets_are_atomic_and_count_rejected_attempt_capacity(self):
        with tempfile.TemporaryDirectory() as value:
            store = Store(Path(value))
            store.initialize()
            entries = [
                ("install", "a", 86400, 6, 10),
                ("global", "global", 86400, 6, 20),
            ]
            self.assertTrue(store.reserve_byte_budgets(entries))
            self.assertFalse(store.reserve_byte_budgets(entries))
            self.assertTrue(
                store.reserve_byte_budgets(
                    [
                        ("install", "b", 86400, 6, 10),
                        ("global", "global", 86400, 6, 20),
                    ]
                )
            )


class StoreMigrationTests(unittest.TestCase):
    def test_existing_capture_table_gains_capture_kind_without_data_loss(self):
        with tempfile.TemporaryDirectory() as value:
            root = Path(value)
            connection = sqlite3.connect(root / "telemetry.sqlite3")
            try:
                connection.execute(
                    """
                    CREATE TABLE captures (
                        capture_id TEXT PRIMARY KEY,
                        install_id TEXT NOT NULL,
                        sha256 TEXT NOT NULL UNIQUE,
                        relative_path TEXT NOT NULL UNIQUE,
                        received_at INTEGER NOT NULL,
                        compressed_bytes INTEGER NOT NULL,
                        uncompressed_bytes INTEGER NOT NULL,
                        sample_count INTEGER NOT NULL,
                        schema_version INTEGER NOT NULL,
                        app_version TEXT NOT NULL,
                        source_address_hash TEXT NOT NULL
                    )
                    """
                )
                connection.execute(
                    "INSERT INTO captures VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                    ("old", "a" * 32, "b" * 64, "accepted/old.zip", 1, 2, 3, 4, 5, "0.8.0", "source"),
                )
                connection.commit()
            finally:
                connection.close()

            store = Store(root)
            store.initialize()
            with store.connect() as connection:
                row = connection.execute(
                    "SELECT capture_id, capture_kind FROM captures WHERE capture_id='old'"
                ).fetchone()
            self.assertEqual("old", row["capture_id"])
            self.assertEqual("raw_debug", row["capture_kind"])


class EnrollmentTests(unittest.TestCase):
    def test_installation_enrolls_without_invite_and_keeps_key_binding(self):
        with tempfile.TemporaryDirectory() as value:
            store = Store(Path(value))
            store.initialize()
            store.enroll("a" * 32, "modulus", "exponent")
            installation = store.installation("a" * 32)
            self.assertIsNotNone(installation)
            self.assertEqual("active", installation["status"])
            store.enroll("a" * 32, "modulus", "exponent")
            with self.assertRaisesRegex(ValueError, "different key"):
                store.enroll("a" * 32, "other-modulus", "exponent")

    def test_registry_cap_is_atomic_and_existing_identity_still_refreshes(self):
        with tempfile.TemporaryDirectory() as value:
            store = Store(Path(value))
            store.initialize()
            maximum = 5

            def enroll(index: int) -> bool:
                try:
                    store.enroll(
                        f"{index:032x}",
                        f"modulus-{index}",
                        "exponent",
                        maximum_installations=maximum,
                        idle_retention_days=30,
                    )
                    return True
                except InstallationRegistryFullError:
                    return False

            with concurrent.futures.ThreadPoolExecutor(max_workers=12) as executor:
                accepted = list(executor.map(enroll, range(20)))

            with store.connect() as connection:
                count = connection.execute("SELECT COUNT(*) FROM installations").fetchone()[0]
            self.assertEqual(maximum, count)
            self.assertEqual(maximum, sum(accepted))

            first = next(index for index, was_accepted in enumerate(accepted) if was_accepted)
            store.enroll(
                f"{first:032x}",
                f"modulus-{first}",
                "exponent",
                maximum_installations=maximum,
                idle_retention_days=30,
            )

    def test_prune_removes_only_stale_unreferenced_installations(self):
        with tempfile.TemporaryDirectory() as value:
            store = Store(Path(value))
            store.initialize()
            stale = "a" * 32
            referenced = "b" * 32
            current = "c" * 32
            for install_id in (stale, referenced, current):
                store.enroll(install_id, f"modulus-{install_id}", "exponent")

            with store.connect() as connection:
                connection.execute(
                    "UPDATE installations SET last_seen=0 WHERE install_id IN (?, ?)",
                    (stale, referenced),
                )
                connection.execute(
                    """
                    INSERT INTO captures(
                        capture_id, install_id, sha256, relative_path, received_at,
                        compressed_bytes, uncompressed_bytes, sample_count,
                        schema_version, app_version, source_address_hash)
                    VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        "capture",
                        referenced,
                        "d" * 64,
                        "accepted/reference.zip",
                        1,
                        1,
                        1,
                        1,
                        5,
                        "0.7.4",
                        "source",
                    ),
                )

            removed = store.prune_installations(idle_retention_days=30)
            self.assertEqual(1, removed)
            self.assertIsNone(store.installation(stale))
            self.assertIsNotNone(store.installation(referenced))
            self.assertIsNotNone(store.installation(current))


if __name__ == "__main__":
    unittest.main()
