import base64
import tempfile
import unittest
import zipfile
from pathlib import Path

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa

from app.security import canonical_capture, public_key, verify_signature
from app.store import Store
from app.validation import validate_capture


ROOT = Path(__file__).resolve().parents[1]
HEADER = (ROOT / "schema-v5.header").read_text(encoding="utf-8").strip()


class CaptureValidationTests(unittest.TestCase):
    def _archive(self, directory: Path, row_values=None, session_count=1) -> Path:
        values = row_values or ["0"] * len(HEADER.split(","))
        values[0] = "1"
        path = directory / "capture.zip"
        with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
            archive.writestr("telemetry.csv", HEADER + "\n" + ",".join(values) + "\n")
            archive.writestr(
                "session.txt",
                "Generated by test\n"
                "telemetry_schema=5\n"
                "source_period=SIM_FRAME\n"
                f"sample_count={session_count}\n",
            )
        return path

    def test_accepts_current_schema_archive(self):
        with tempfile.TemporaryDirectory() as value:
            facts = validate_capture(self._archive(Path(value)), HEADER, 64 * 1024 * 1024)
            self.assertEqual(1, facts.sample_count)
            self.assertGreater(facts.uncompressed_bytes, 0)

    def test_rejects_non_finite_value(self):
        with tempfile.TemporaryDirectory() as value:
            row = ["0"] * len(HEADER.split(","))
            row[0] = "1"
            row[1] = "nan"
            with self.assertRaisesRegex(ValueError, "not finite"):
                validate_capture(self._archive(Path(value), row), HEADER, 64 * 1024 * 1024)

    def test_rejects_unexpected_member(self):
        with tempfile.TemporaryDirectory() as value:
            path = self._archive(Path(value))
            with zipfile.ZipFile(path, "a", compression=zipfile.ZIP_DEFLATED) as archive:
                archive.writestr("surprise.bin", b"garbage")
            with self.assertRaisesRegex(ValueError, "exactly"):
                validate_capture(path, HEADER, 64 * 1024 * 1024)

    def test_rejects_count_mismatch(self):
        with tempfile.TemporaryDirectory() as value:
            with self.assertRaisesRegex(ValueError, "sample_count"):
                validate_capture(self._archive(Path(value), session_count=2), HEADER, 64 * 1024 * 1024)


class SignatureTests(unittest.TestCase):
    def test_capture_signature_is_bound_to_hash_and_size(self):
        private = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        numbers = private.public_key().public_numbers()
        modulus = base64.b64encode(numbers.n.to_bytes(256, "big")).decode("ascii")
        exponent = base64.b64encode(numbers.e.to_bytes(3, "big")).decode("ascii")
        message = canonical_capture(
            "a" * 32,
            "2026-08-05T12:00:00Z",
            "A" * 22,
            "b" * 64,
            1234,
            5,
            "0.7.0",
        )
        signature = private.sign(message, padding.PKCS1v15(), hashes.SHA256())
        encoded = base64.b64encode(signature).decode("ascii")
        verify_signature(public_key(modulus, exponent), message, encoded)
        with self.assertRaisesRegex(ValueError, "verification failed"):
            verify_signature(public_key(modulus, exponent), message + b"x", encoded)


class ByteBudgetTests(unittest.TestCase):
    def test_byte_budgets_are_atomic_and_count_rejected_attempt_capacity(self):
        with tempfile.TemporaryDirectory() as value:
            store = Store(Path(value))
            store.initialize()
            entries = [
                ("install", "a", 86400, 6, 10),
                ("global", "global", 86400, 6, 20),
            ]
            self.assertTrue(store.reserve_byte_budgets(entries))
            self.assertFalse(store.reserve_byte_budgets(entries))
            self.assertTrue(
                store.reserve_byte_budgets(
                    [
                        ("install", "b", 86400, 6, 10),
                        ("global", "global", 86400, 6, 20),
                    ]
                )
            )


if __name__ == "__main__":
    unittest.main()
