using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Text;
using LandingStats.Core;

namespace LandingStats.App.Storage;

public sealed class RawCaptureRepository
{
    public RawCaptureRepository(string? rootPath = null)
    {
        RootPath = rootPath ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "MSFS Landing Stats",
            "Raw Captures");
    }

    public string RootPath { get; }

    public string Save(
        IReadOnlyList<TelemetrySample> samples,
        string simulator,
        string aircraftTitle,
        string aircraftType,
        string aircraftModel,
        DateTime timestampUtc)
    {
        if (samples == null)
        {
            throw new ArgumentNullException(nameof(samples));
        }

        Directory.CreateDirectory(RootPath);
        var captureId = Guid.NewGuid().ToString("N");
        var safeTimestamp = timestampUtc.ToString("yyyyMMdd_HHmmss'Z'", CultureInfo.InvariantCulture);
        var path = Path.Combine(RootPath, $"{safeTimestamp}_{captureId}_raw.zip");
        var temporaryPath = path + ".tmp";

        try
        {
            using (var file = new FileStream(temporaryPath, FileMode.CreateNew, FileAccess.Write, FileShare.None))
            using (var archive = new ZipArchive(file, ZipArchiveMode.Create, false))
            {
                WriteTelemetry(archive, samples);
                WriteSession(
                    archive,
                    samples,
                    timestampUtc,
                    simulator,
                    aircraftTitle,
                    aircraftType,
                    aircraftModel);
            }

            File.Move(temporaryPath, path);
            return path;
        }
        catch
        {
            if (File.Exists(temporaryPath))
            {
                File.Delete(temporaryPath);
            }

            throw;
        }
    }

    private static void WriteTelemetry(ZipArchive archive, IReadOnlyList<TelemetrySample> samples)
    {
        var entry = archive.CreateEntry("telemetry.csv", CompressionLevel.Optimal);
        using (var stream = entry.Open())
        using (var writer = new StreamWriter(stream, new UTF8Encoding(false), 65536, false))
        {
            writer.WriteLine(TelemetryCsv.Header);
            foreach (var sample in samples)
            {
                writer.WriteLine(TelemetryCsv.Format(sample));
            }
        }
    }

    private static void WriteSession(
        ZipArchive archive,
        IReadOnlyList<TelemetrySample> samples,
        DateTime timestampUtc,
        string simulator,
        string aircraftTitle,
        string aircraftType,
        string aircraftModel)
    {
        var entry = archive.CreateEntry("session.txt", CompressionLevel.Optimal);
        using (var stream = entry.Open())
        using (var writer = new StreamWriter(stream, new UTF8Encoding(false), 4096, false))
        {
            writer.WriteLine($"Generated by MSFS Landing Stats {ApplicationVersion()}");
            writer.WriteLine($"capture_utc={timestampUtc.ToString("O", CultureInfo.InvariantCulture)}");
            writer.WriteLine($"telemetry_schema={TelemetryCsv.SchemaVersion.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine("source_period=SIM_FRAME");
            writer.WriteLine("sample_policy=all_received_frames_no_downsampling");
            writer.WriteLine($"sample_count={samples.Count.ToString(CultureInfo.InvariantCulture)}");
            writer.WriteLine($"simulator={SingleLine(simulator)}");
            writer.WriteLine($"aircraft_title={SingleLine(aircraftTitle)}");
            writer.WriteLine($"aircraft_type={SingleLine(aircraftType)}");
            writer.WriteLine($"aircraft_model={SingleLine(aircraftModel)}");
        }
    }

    private static string ApplicationVersion()
    {
        var assembly = typeof(RawCaptureRepository).Assembly;
        var informational = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
        return informational?.InformationalVersion ?? assembly.GetName().Version?.ToString() ?? "unknown";
    }

    private static string SingleLine(string? value)
    {
        return string.IsNullOrWhiteSpace(value)
            ? "unknown"
            : value!.Trim().Replace("\r", " ").Replace("\n", " ");
    }
}
